"use client";

import { useEffect, useState, useCallback } from "react";
import { useParams, useRouter } from "next/navigation";
import { doc, getDoc, updateDoc } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { useAuth } from "@/lib/auth-context";
import { Header } from "@/components/header";
import { Sidebar } from "@/components/sidebar";
import { TaskDetail } from "@/components/task-detail";
import { isDemoMode, getDemoTask } from "@/lib/demo-mode";
import type { Task } from "@/lib/types";
import { RichTaskView } from "@/components/rich-task-view";

interface RichTaskData {
  issueUrl?: string;
  目的?: string;
  説明?: string;
  必要な知識?: string;
  ロードマップ?: string;
  ステップ?: {
    やること: string;
    公式教材のリンク: string;
    ヘルプ: string;
    答え: string;
  }[];
}

export default function TaskPage() {
  const params = useParams();
  const router = useRouter();
  const { user, loading: authLoading } = useAuth();
  const [task, setTask] = useState<Task | null>(null);
  const [richData, setRichData] = useState<RichTaskData | null>(null);
  const [activeStepId, setActiveStepId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  const projectId = params.project as string;
  const taskId = params.taskId as string;
  const demoMode = isDemoMode();

  useEffect(() => {
    if (!authLoading && !user) {
      router.push("/login");
      return;
    }

    if (demoMode) {
      const demoTask = getDemoTask(taskId);
      if (demoTask) {
        setTask({ ...demoTask, projectId });
      }
      setLoading(false);
      return;
    }

    const fetchTask = async () => {
      try {
        const taskDoc = await getDoc(doc(db, "tasks", taskId));
        if (taskDoc.exists()) {
          const data = taskDoc.data();
          setTask({ id: taskDoc.id, ...data } as Task);
          // Extract rich task data if available (generated by analyze-issue)
          if (data["目的"] !== undefined) {
            setRichData({
              issueUrl: data.issueUrl,
              目的: data["目的"],
              説明: data["説明"],
              必要な知識: data["必要な知識"],
              ロードマップ: data["ロードマップ"],
              ステップ: data["ステップ"],
            });
          }
        }
      } catch {
        // Task not found - use fallback demo data
        setTask(createFallbackTask(taskId, projectId));
      }
      setLoading(false);
    };

    if (!authLoading) {
      fetchTask();
    }
  }, [taskId, projectId, user, authLoading, router, demoMode]);

  const handleToggleCompletion = useCallback(
    async (stepId: string) => {
      if (!task) return;

      const updatedSteps = task.steps.map((step) =>
        step.id === stepId ? { ...step, completed: !step.completed } : step
      );

      const updatedTask = { ...task, steps: updatedSteps };
      setTask(updatedTask);

      if (demoMode) {
        return;
      }

      try {
        await updateDoc(doc(db, "tasks", task.id), { steps: updatedSteps });
      } catch {
        // Firestore update failed, keep local state
      }
    },
    [task, demoMode]
  );

  const handleStepClick = useCallback((stepId: string) => {
    setActiveStepId(stepId);
  }, []);

  const handleStartStep = useCallback((stepId: string) => {
    setActiveStepId(stepId);
  }, []);

  if (loading || authLoading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-gray-50">
        <div className="text-sm text-gray-400">読み込み中...</div>
      </div>
    );
  }

  if (!task) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-gray-50">
        <div className="text-sm text-gray-400">
          タスクが見つかりませんでした
        </div>
      </div>
    );
  }

  const completedSteps = task.steps.filter((s) => s.completed).length;
  const progress = Math.round((completedSteps / task.steps.length) * 100);
  const activeStep =
    task.steps.find((s) => s.id === activeStepId) ?? null;

  // If task was generated from an Issue (has rich fields), show the rich view
  if (richData) {
    return (
      <div className="flex h-screen flex-col bg-gray-50">
        <Header
          breadcrumbs={[
            { label: "カリキュラム", href: `/${projectId}` },
            { label: richData.目的 ?? task.title },
          ]}
        />
        <div className="flex-1 overflow-auto">
          <RichTaskView
            richData={richData}
            task={task}
            onToggleCompletion={handleToggleCompletion}
          />
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-screen flex-col bg-gray-50">
      <Header
        breadcrumbs={[
          { label: "カリキュラム", href: `/${projectId}` },
          { label: task.title },
        ]}
      />
      <div className="flex flex-1 overflow-hidden">
        <Sidebar
          title={task.title}
          description={task.description}
          steps={task.steps}
          activeStepId={activeStepId}
          progress={progress}
          onStepClick={handleStepClick}
          onStartStep={handleStartStep}
        />
        <TaskDetail
          task={task}
          activeStep={activeStep}
          onToggleCompletion={handleToggleCompletion}
        />
      </div>
    </div>
  );
}

function createFallbackTask(taskId: string, projectId: string): Task {
  return {
    id: taskId,
    projectId,
    title: "LPのヘッダー作成",
    description:
      "Flexboxレイアウトをマスターして、メインナビゲーションコンポーネントを構築しましょう。",
    assigneeId: "",
    status: "published",
    createdAt: new Date(),
    steps: [
      {
        id: "step-1",
        title: "Flexboxのドキュメントを読む",
        description: "MDNのFlexboxガイドを読んで基本概念を理解します。",
        estimatedMinutes: 10,
        referenceUrl:
          "https://developer.mozilla.org/ja/docs/Web/CSS/CSS_flexible_box_layout",
        completed: true,
      },
      {
        id: "step-2",
        title: "リポジトリをクローンする",
        description: "開発用のブランチを作成してローカルに準備します。",
        estimatedMinutes: 5,
        command: "git checkout -b feature/header",
        completed: true,
      },
      {
        id: "step-3",
        title: "Header.tsx の構造を理解する",
        description: "提供されたスターターコードを分析します。",
        estimatedMinutes: 10,
        referenceUrl: "https://react.dev/learn",
        completed: false,
      },
      {
        id: "step-4",
        title: "ナビゲーションリンクの実装",
        description: "Flexboxを使ってナビゲーションリンクを横並びに配置します。",
        estimatedMinutes: 15,
        completed: false,
      },
      {
        id: "step-5",
        title: "Tailwind クラスの適用",
        description:
          "デザイン仕様に合わせてTailwind CSSクラスを適用します。",
        estimatedMinutes: 20,
        command:
          'className="flex items-center justify-between h-16 px-6 bg-white border-b border-gray-200"',
        completed: false,
      },
    ],
  };
}
